### ISSUE TITLE
Is Alignment plugin not supported yet?

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5-table#104]
I think Alignment toolbar is not enabled when Table is selected in editor.

Is it supported ?(may be I have something wrong on end)

Or will it be supported in near future ?

**Comment by jodator** [comment]
The support for block contents is on its way: #56. It will enable Alignment feature on paragraphs, headings, lists, etc inside table cells: #96.

**Comment by Reinmar** [comment]
I think that the question was about aligning the entire table to the left/right/center. That will be done like the image styles. But do we have a ticket for table styles?

**Comment by gauravjain028** [comment]
Thanks @jodator and @Reinmar 

Sorry for short description. My concern was for both, alignment for content of table and for table itself.

**Comment by jodator** [comment]
@Reinmar as for table styles (as in image styles) AFAICS we do not have a ticket yet. I'll create it for table styles so we can track both.

**Comment by jodator** [comment]
@gauravjain028 & @Reinmar : the ticket for table styles is here: #105.
