### ISSUE TITLE
Make table ui utils more generic

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-table#106]
The `getBalloonPositionData` would be more useful if this function could handle a case when the selection is on the table element, not inside it. This util might be used then to position another table toolbar - that could have an option to add a comment to the whole table.

The second issue I see with it is that this code a little bit repeats across `ckeditor5-image`, `ckeditor5-table` and will repeat in the `ckeditor5-media-embed` in the future. Maybe it could be extracted to `ckeditor5-core` or `ckeditor5-ui`?

WDYT @jodator?

**Comment by jodator** [comment]
@ma2ciek as for duplicated code - yes it should be deduplicated but we left that as is while implementing table (time constrains). I thought we had this issue reported somewhere but I couldn't find it.

The `getBalloonPositionData` - Yeah - looks like it might be handy for that case.

**Comment by ma2ciek** [comment]
It will be closed by the https://github.com/ckeditor/ckeditor5-widget/pull/54.
