### ISSUE TITLE
"splitResult is null" on paste HTML code including a nested table

### ISSUE THREAD

**Issue by cedx** [ckeditor/ckeditor5-table#131]
Sometimes, when I paste some text copied from a Web page including a table, the editor seems to freeze, and the following error raises in the browser console :

```
splitResult is null
```

This error comes from the following line :
https://github.com/ckeditor/ckeditor5-table/blob/master/src/converters/upcasttable.js#L54

**Comment by jodator** [comment]
@cedx could you provide some example content that causes this bug?

**Comment by cedx** [comment]
OK, finally found the root cause : nested tables.

Open this HTML file, select all its content (`Ctrl + A`) and copy/paste it to an instance of the editor :

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>

  <body>
    <table>
      <tbody>
        <tr>
          <td>Foo</td>
          <td>
            <table>
              <tr>
                <td>Bar</td>
              </tr>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
```

**Comment by Reinmar** [comment]
This is a dup of https://github.com/ckeditor/ckeditor5/issues/1260. It's fixed on master already and I checked that it's not possible to reproduce the bug in the nightly docs (https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/table.html).

However, nested tables are not supported yet and this is tracked in https://github.com/ckeditor/ckeditor5-table/issues/121. We'd like to gather feedback when they are needed. What are the use cases.

**Comment by cedx** [comment]
Thanks, I'll wait for the next release 😃 

What are the use cases? Not a true usage, just bad habits.
In my company, we have a knowledge base that uses the CKEditor for creating content. It is very common for users to copy and paste content from existing web pages, rather than creating text from scratch.

That's why we have nested tables : they don't come from the users, but from external content. On old websites (and unfortunately also on a few recent websites), nested tables are very common.
So my need is not about editing nested tables, but just to be able to display them inside the editor.

Another thanks for the wonderful job done: I'm very impressed by the version 5 of the editor. 👏
