### ISSUE TITLE
The insert command should be disabled when media are selected

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-table#148]
Even if it inserts the table after the media, it makes no sense IMO

![image](https://user-images.githubusercontent.com/1099479/48762634-bb419400-ecab-11e8-81fe-997241ac7e46.png)

cc @jodator

**Comment by Reinmar** [comment]
Can't you insert a table over the embed? I don't see why we should disable that command. While people may not use it very often, it should not harm anyone.
