### ISSUE TITLE
Table cell image upload causes TypeError on editor initialisation

### ISSUE THREAD

**Issue by J-Nagle** [ckeditor/ckeditor5-table#157]
As mentioned in https://github.com/ckeditor/ckeditor5-image/pull/262#issuecomment-448417927, using the latest masters of Table, Image, Engine, Widget and Block Quoting to enable uploading images directly inside table cells, the functionality causes a `TypeError: Object doesn't support property or method 'has'` when first loading in. To demonstrate, add the attached resources to [this JSFiddle](https://jsfiddle.net/bznmLodv/).

[CKEditor - Table image upload test build.zip](https://github.com/ckeditor/ckeditor5-table/files/2701130/CKEditor.-.Table.image.upload.test.build.zip)

**Comment by jodator** [comment]
@J-Nagle sorry for longer reply but we were fixing various table & image & blockquote related bugs. As for now it looks like the issue is no longer reproducible. The `plugin.has` is on master from some time so this shouldn't occur now.

**Comment by J-Nagle** [comment]
After some trouble producing a working build and a small update to resolve an API change, we confirmed the latest changes solve this. Thanks a lot for your hard work.

**Comment by jodator** [comment]
Thanks! :blush: Great to hear that everything works.

> a small update to resolve an API change

yeah... sorry about that next release is going to introduce some breaking changes so it might be some more updates to come on master.
