### ISSUE TITLE
Editor crashes after adding a blockquote to a widget

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-table#163]
## Steps to reproduce
1. Create a table.
1. Insert an image to a table cell.
1. Focus the image.
1. Add a blockquote.

## Current result
The editor crashes.

## Error
```
renderer.js:724 The given range isn't in document.
```

**Comment by Reinmar** [comment]
cc @jodator

**Comment by jodator** [comment]
ps.: As such I'll express the idea/concept of `selectionRoot` which I have when I deal with selection post-fixing - the lowest `isLimit` element acts as `selectionRoot` as it does not allow selection to cross its boundaries. Right now I think that only `<tableCell>` is such entity and defining seperate `schama.isFoo()` is not necessary. The other element that might behave like this could be `<codeBlock>` - if we'd like to introduce collaboration features inside it (selection, copy/paste, comments on code).
