### ISSUE TITLE
Remove support for deprecated `table.toolbar`.

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-table#167]
In the next major release, we should remove that property from being supported.

**Comment by oleq** [comment]
When was it deprecated and by what?

**Comment by ma2ciek** [comment]
It was deprecated in the https://github.com/ckeditor/ckeditor5-table/releases/tag/v11.0.0.

Actually, it's already in the `BREAKING CHANGES`... I guess it was a mistake. We could skip the warning and remove the support for it since we had other breaking changes in that release.
