### ISSUE TITLE
Toolbar for the `tableContent` breaks the editor if the document selection isn't initialized

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-table#168]
The `WidgetToolbarRepository` class tries to update toolbars whenever there's a UI update. Although it might happen that the editor isn't fully initialized yet and it can contain an unset document selection (with no ranges). Then, if the toolbar for the `tableContent` is registered, the `getTableWidgetAncestor` util is invoked with a selection that doesn't which `selection.getFirstPosition()` is equal to `null`.

https://github.com/ckeditor/ckeditor5-table/blob/3fc2b17f8da072ec984a5d6fe01a3f2ad98c42c0/src/tabletoolbar.js#L64-L67

https://github.com/ckeditor/ckeditor5-table/blob/3fc2b17f8da072ec984a5d6fe01a3f2ad98c42c0/src/utils.js#L63-L70

**Comment by jodator** [comment]
Isn't that a `widgetToolbarRepository` bug? the `getTableWidgateAncestor()` shouldn't be called if the editor is not initialized fully. The `if()` would be redundant as `WidgetToolbarRepository` should call those methods in proper moment.

**Comment by jodator** [comment]
Another thing is that the toolbar is registered in `afterInit()` so I'd expect the editor to be initialized. Isn't that related somehow to the latest changes in editor events/startup? This assumption might be invalid as I didn't follow those changes. //cc @pjasiun

**Comment by ma2ciek** [comment]
> Another thing is that the toolbar is registered in `afterInit()`.

Oh, I missed it, good point. I'll check more deeply this bug.

**Comment by ma2ciek** [comment]
Closed in favor of https://github.com/ckeditor/ckeditor5-engine/issues/1653.
