### ISSUE TITLE
Is it possible to align tables to the left/right instead of centre without resorting to CSS

### ISSUE THREAD

**Issue by statler** [ckeditor/ckeditor5-table#170]
When a table is used, it is automatically stuck in the middle of the page. Can it be aligned left or right without changing the css of the table container? 

e.g. .ck-content .table {
    margin: 1em ~~auto~~;
}

**Comment by Reinmar** [comment]
Hi! Do you mean "Align left" and "Align right" buttons? Or something else?

**Comment by jodator** [comment]
From the CSS I think that it is dup of: #105.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
