### ISSUE TITLE
[Firefox] Unable to navigate with arrow keys inside table

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-table#175]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest `master` and `v11.1.1`

## 📋 Steps to reproduce

1. Go to https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html.
2. Focus table inside editor.
3. Try to navigate with arrow keys between table cells.

## ✅ Expected result

It is possible to navigate with arrow keys between cells.

## ❎ Actual result

Nothing happens.

## 📃 Other details that might be useful

Tested with Firefox `65.0.1 (64-bit)` on macOS `10.13.6 (17G65)`.

It works fine on Chrome. From what I have found in the https://github.com/ckeditor/ckeditor5-table/issues/108#issuecomment-419114747 this behaviour is left for the browser to handle so I'm not sure if it worked in Firefox earlier (doesn't work with `v11.1.1`). It works fine when table is placed inside contenteditable (tested without CKEditor).

**Comment by jodator** [comment]
@f1ames That worked on Firefox some time ago - at least when the plugin was created. There was even mismatch in that behavior between browsers. In Firefox you could use arrow up/down to go to previous/next row. On Chrome you'd go to previous/next cell hence the #108 issue was created.

ps.: I liked the FF implementation more.

**Comment by jodator** [comment]
I've checked the:
- https://ckeditor.com/docs/ckeditor5/11.0.1/examples/builds/document-editor.html
- https://ckeditor.com/docs/ckeditor5/11.1.0/examples/builds/document-editor.html

Both are not working so I guess something happened to the FF.

**Comment by f1ames** [comment]
I have checked with Firefox `59`, `62`, `63` (on Browserstack) with `11.1.1` and `11.0.1` and it doesn't work there either.

**Comment by Reinmar** [comment]
I don't think this ever worked. There were differences between browsers from the very beginning and I think it was one of them. 

In any case, let's keep all those navigation issues in one place. Merging to https://github.com/ckeditor/ckeditor5-table/issues/108
