### ISSUE TITLE
Support column width resize

### ISSUE THREAD

**Issue by gastonmunoz** [ckeditor/ckeditor5-table#190]
Allow a table plugin for column resize, with a number in balloon or mouse resize.

There is an attached example.
[example.txt](https://github.com/ckeditor/ckeditor5-table/files/3192029/example.txt)

**Comment by Mgsy** [comment]
Hello, this feature is on our roadmap and we'll be definitely working on it. It's a part of Milestone 2 for the table plugin. You can read more in this [issue](https://github.com/ckeditor/ckeditor5-table/issues/3).
