### ISSUE TITLE
Write a guide for the feature

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-table#32]
Just like other features, tables should have their own guide in the ["Features"](https://docs.ckeditor.com/ckeditor5/latest/features/index.html) section explaining basic concepts, configuration and providing demos for developers.

Without the guide, it's hard to release the feature to the public.

**Comment by Reinmar** [comment]
I think that this guide can be very simple for now:

1. Super brief intro
2. Demo
3. How to install + note that this feature is available at the moment only in the document build,
4. Common API (can be a link to API docs because this will be too many things to cover) a
5. Contribute
