### ISSUE TITLE
Table toolbar shouldn't be displayed when whole table is selected

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#36]
... at least until we have table styles or something applicable to whole table as now it's disabled:

![selection_001](https://user-images.githubusercontent.com/247363/41151458-16c3dd50-6b11-11e8-8343-32dbc9ca9e11.png)

It should be only visible when selection is inside table cell:

![selection_002](https://user-images.githubusercontent.com/247363/41151477-25c96f36-6b11-11e8-8b0d-3f2eef425829.png)

It's after the #28 fix I think.

**Comment by Reinmar** [comment]
Agree. The toolbar should only be visible when it can be used. Also, the whole table may have a different toolbar (e.g. with table styles).

**Comment by oleq** [comment]
Funny you should mention that because I enabled it on purpose in latest refac because I felt it's weird that it disappeared in such situation :P Well, maybe I was wrong, hard to tell.

It's easy to change, BTW

```diff
diff --git a/src/tabletoolbar.js b/src/tabletoolbar.js
index 076d11b..01b9377 100644
--- a/src/tabletoolbar.js
+++ b/src/tabletoolbar.js
@@ -114,7 +114,7 @@ export default class TableToolbar extends Plugin {
                   } else {
                            const viewSeleciton = editor.editing.view.document.selection;

-                           if ( isTableWidgetSelected( viewSeleciton ) || isTableContentSelected( viewSeleciton ) ) {
+                           if ( isTableContentSelected( viewSeleciton ) ) {
                                     this._showToolbar();
                            } else {
                                     this._hideToolbar();
```
