### ISSUE TITLE
Review button and command names

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-table#58]
I'd like us to take a final look at the commands and buttons exposed by this feature.

E.g. I've noticed that the `table.toolbar` option is set to: `[ 'tableCell', 'tableRow', 'mergeCell' ]`.

My first thoughts were:

* `tableColumn` and `tableRow` are overly generic. Perhaps `tableColumnActions`? OTOH... KISS?
* `mergeCell` – similarly generic and not true now, because it doesn't merge anything. But we plan to make it a split button soon, so it will merge cells. Exactly – cells, not a cell. Hence, WDYT about `mergeCells`?

It'd be good to check other commands and buttons too. I haven't paid much attention to them earlier because we didn't know what UI we'll end up with.

**Comment by jodator** [comment]
Yeah - I've used simpler names as we do not have `headingActions` or similar things in other dropdowns.

Them `mergeCells` might be not-so-distant-future proof so :+1:.

> [ 'tableCell', 'tableRow', 'mergeCell' ]

ps.: it's `'tableColumn'` not `'tableCell'` but I'm sure it's just typo :)

**Comment by Reinmar** [comment]
> ps.: it's 'tableColumn' not 'tableCell' but I'm sure it's just typo :)

Yup, typo.

**Comment by Reinmar** [comment]
I'd also change these two commands:

```
"setColumnHeader"
"setRowHeader"
```

to `setTable...`

**Comment by Reinmar** [comment]
OK, and I see that no UI components other than the 3 main ones are registered in the component factory. So we don't need to be that cautious about names of these classes.

**Comment by Reinmar** [comment]
> to setTable...

Hm... we'd also need to rename `insertColumnAfter` to `insertTableColumnAfter`, `removeRow` to `removeTableRow`. WDYT?
