### ISSUE TITLE
Table widget & table navigation

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#7]
The next mini-milestone after #4 to implement table feature MVP.

Things I'd like to see covered here would be:
- table as a widget
- cursor navigation through table cells with arrows & tab
- entering/leaving a table
- selection handling (cell, row/column) - if not a bigger task itself

I'll post another comment here when doing selection - how to handle and display as it might require some [minor UI/UX research](https://github.com/ckeditor/ckeditor5-table/issues/1#issuecomment-341427427) first.

Also I'm open to any suggestions/tips beyond current specs that we have.

**Comment by jodator** [comment]
So I'd like to propose caret movement behavior:

1. Without SHIFT:
    - UP, DOWN arrows: moves caret to the table cell in previous, next row (on the same column index or to a spanned cell)
    - LEFT, RIGHT arrows on the table cell's content edge - skip to next, previous cell, exit table on the first/last table cell
    - TAB go to next cell, or exit table
2. With SHIFT - as above but will expand selection. The question is whether to select whole table cells (I'd go with selecting whole table cells)
3. MOUSE - selecting whole table cells

The other thing is how to (if wanted by us) to show selection of the whole table cell on caret movement.

I've checked how gdocs does it for example and they have two-step carret movement on the table cell edges. Basically the second step selects whole table cell:

![selection_022](https://user-images.githubusercontent.com/247363/38605731-715a9d3c-3d74-11e8-9ba0-3aad464c798d.png) ---- second step ---> ![selection_023](https://user-images.githubusercontent.com/247363/38605735-72c4343a-3d74-11e8-9659-61d995e18c05.png)

/cc @Reinmar, @oleq, @dkonopka

**Comment by Reinmar** [comment]
@jodator Could you check how these keys work in CKEditor 4? E.g. Tab in the last cell creates a new row. And I think left and top had the same behaviour. 

Besides, we don't have cell selection in the [MVP](https://github.com/ckeditor/ckeditor5-table/issues/3). Row/col/cells selection is in milestone 2.

**Comment by jodator** [comment]
@Reinmar ahh yes, you're right. So dropping the cell selection for now - only the caret movement. So probably only minor tweaks to default caret movement and to unify browsers behavior (Chrome acts differently then Firefox on up/down arrows).

As for CKE4:
- the TAB in the last cell creates another row
- the SHIFT-TAB on the first table cell doesn't do anything (the caret stays there)
- the arrows movement is as in browser (so Chrome & Firefox acts differently on up/down)

> And I think left and top had the same behaviour.

could you explain this part - I'm not sure what you've meant here

**Comment by Reinmar** [comment]
> could you explain this part - I'm not sure what you've meant here

I thought that left and top have the same behaviour at the beginning of a table cell. But from what you wrote it depends on which browser you test. So – it means that CKE4 does not unify this behaviour and I think we can skip it in CKE5 as well. At least initially.
