### ISSUE TITLE
Merging down double-row header cell results in broken table

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-table#86]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

`v10.1.0`

## 📋 Steps to reproduce

1. Go to https://docs.ckeditor.com/ckeditor5/latest/features/table.html.
1. Place selection in the top-left cell.
1. Open merging/splitting panel and apply `Merge cell down`.

![table1](https://user-images.githubusercontent.com/1061942/42636563-675c7860-85e9-11e8-923c-9c25768d34fb.gif)

## ✅ Expected result

Cell is correctly merged.

## ❎ Actual result

Cell is not merged and the cell below disappears.

## 📃 Other details that might be useful

Tested on Chrome `67.0.3396.99 `.

Looks like this is the issue with `thead`, works fine if there is only `tbody`. Also if `thead` is a single row, `Merge cell down` option is disabled.

**Comment by jodator** [comment]
> Cell is correctly merged.

The expected result is that the merge shouldn't be possible - the mege would cross `<thead>` & `<tbody>` boundary which isn't allowed - now this happens:
```html
<th class="ck-editor__editable ck-editor__nested-editable" rowspan="3" contenteditable="true">
```
so this table cell is properly expaneded, the cell is merged with one below but the browser (correctly) doesn't render this and we have a collision.

Probably an easy/small fix though.
