### ISSUE TITLE
Add images (nested widgets) support in tables.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#99]
Follow-up for the #56 - currently there are some issues with widget in widget (images in tables):

- click select does not work
- ballon toolbar sometimes does not work
- pasted image behaves differently then converted from data - you can edit caption only for pasted
- fake selection sometimes is broken

**Comment by Reinmar** [comment]
I guess that images are now allowed (by the schema) in tables. Am I right? So the iteration 20 won't be complete unless we close this ticket or disallow images in tables?

**Comment by Reinmar** [comment]
I'm asking because we need to do either A or B.

**Comment by jodator** [comment]
> I guess that images are now allowed (by the schema) in tables. Am I right? So the iteration 20 won't be complete unless we close this ticket or disallow images in tables?

You're guess is incorrect ;) I've disabled it in the #97 PR:
https://github.com/ckeditor/ckeditor5-table/blob/bd5b81d0062cc984d08f6ea456108ede632b7b89/src/tableediting.js#L84-L89

I've disable it after issues with  widget in widget (image in table): #98, #99.

**Comment by Reinmar** [comment]
OK, cool. So we can postpone this.

**Comment by 100cm** [comment]
why disallow image in table cell ? i think we need it...

**Comment by jodator** [comment]
Ref: https://github.com/ckeditor/ckeditor5/issues/1331.
